version: '3.8'
services:
  db:
    image: postgres:15
    container_name: eleastar-postgres
    restart: always
    environment:
      POSTGRES_USER: eleastar_user
      POSTGRES_PASSWORD: eleastar_password
      POSTGRES_DB: eleastar_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
