import React from 'react';

import { Facebook, Twitter, Linkedin, Instagram } from 'lucide-react';

export const BrandFooter: React.FC = () => {

    const navLinks = [
        { id: 'f-1', label: 'Services', url: '/services' },
        { id: 'f-2', label: 'Technologies', url: '/technologies' },
        { id: 'f-3', label: 'Eleastar & You', url: '/eleastar-and-you' },
        { id: 'f-4', label: 'About Eleastar', url: '/about' },
        { id: 'f-5', label: 'Contact', url: '/contact' },
        { id: 'f-6', label: 'New Updates', url: '/new-updates' },
        { id: 'f-7', label: 'Locate Us', url: '/locate-us' }
    ];

    const socialLinks = [
        { id: 's-1', label: 'Facebook', url: '#', icon: Facebook },
        { id: 's-2', label: 'X', url: '#', icon: Twitter },
        { id: 's-3', label: 'Instagram', url: '#', icon: Instagram },
        { id: 's-4', label: 'LinkedIn', url: '#', icon: Linkedin }
    ];

    return (
        <footer className="bg-[#020617] text-white pt-16 pb-8 overflow-hidden relative">
            {/* Top Section: Nav & Socials */}
            <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 mb-16 relative z-10">
                {/* Section 1: Navigation */}
                <div className="col-span-1 md:col-span-2 lg:col-span-3">
                    <nav className="flex flex-wrap gap-x-8 gap-y-4">
                        {navLinks.map(link => (
                            <a
                                key={link.id}
                                href={link.url}
                                className="text-sm font-medium hover:text-brand-400 transition-colors"
                            >
                                {link.label}
                            </a>
                        ))}
                    </nav>
                </div>

                {/* Section 3: Socials & Contact Actions (right aligned on large) */}
                <div className="flex flex-col items-start md:items-end gap-6">
                    <div className="flex gap-4">
                        {socialLinks.map(link => {
                            const Icon = link.icon;
                            return (
                                <a
                                    key={link.id}
                                    href={link.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center hover:bg-brand-600 transition-colors"
                                    aria-label={link.label}
                                >
                                    <Icon size={18} />
                                </a>
                            );
                        })}
                    </div>
                </div>
            </div>

            {/* Middle Section: Utility & Legal */}
            <div className="max-w-7xl mx-auto px-6 mb-20 relative z-10">
                <div className="flex flex-wrap gap-6 mb-8 text-xs text-slate-400 font-medium uppercase tracking-wider items-center">
                    <a href="/privacy-policy" className="hover:text-white transition-colors">
                        Privacy Policy
                    </a>
                    <a href="/terms" className="hover:text-white transition-colors">
                        Terms Of Service
                    </a>
                    <a href="/login" className="hover:text-white transition-colors border-l border-slate-700 pl-6 ml-auto">
                        Admin Login
                    </a>
                    <div className="flex-grow text-right md:flex-grow-0 ml-auto">
                        <span>Copyright © 2026</span>
                        <span className="mx-2">•</span>
                        <span>RC - 7130026</span>
                    </div>
                </div>

                {/* Section 4: Legal Text */}
                <div className="max-w-4xl">
                    <p className="text-[10px] leading-relaxed text-slate-500 text-justify">
                        By opting in, you consent to our use of any personal data you provide (such as your email address and any other details), together with any data generated by your actions on our website in order to create a user profile for the purpose of communicating Eleastar, services offers and other information to you. For more information, please refer to our Privacy Policy.
                    </p>
                </div>
            </div>

            {/* Section 6: Brand Background Element */}
            <div className="w-full flex justify-center items-end absolute bottom-[-5%] left-0 z-0 pointer-events-none opacity-100 mix-blend-overlay">
                <h1 className="text-[18vw] font-bold leading-none tracking-tighter text-brand-600 select-none">
                    Eleastar
                </h1>
            </div>

            {/* Overlay Gradient for readability over the big text if needed, though mix-blend might handle it. 
                Let's add a subtle gradient at the bottom to fade the footer into the page if needed, 
                but usually footer is solid. The user design matches the image which is solid dark blue/black.
            */}
        </footer>
    );
};
