/**
 * Export Utilities for Compliance Reports
 * Handles CSV and PDF export functionality
 */

/**
 * Convert array of objects to CSV format
 */
export function exportToCSV(
    data: any[],
    filename: string = 'export'
): void {
    if (data.length === 0) {
        console.warn('No data to export');
        return;
    }

    // Get headers from first object
    const headers = Object.keys(data[0]);

    // Create CSV content
    const csvContent = [
        headers.join(','), // Header row
        ...data.map(row =>
            headers.map(header => {
                const value = row[header];
                // Handle values with commas, quotes, or newlines
                if (typeof value === 'string' && (value.includes(',') || value.includes('"') || value.includes('\n'))) {
                    return `"${value.replace(/"/g, '""')}"`;
                }
                return value;
            }).join(',')
        )
    ].join('\n');

    // Create blob and download
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

/**
 * Export data as PDF (simple implementation)
 * Note: For production, consider using jsPDF with autoTable plugin
 */
export function exportToPDF(data: any[], title: string, _filename: string): void {
    if (data.length === 0) {
        console.warn('No data to export');
        return;
    }

    const headers = Object.keys(data[0]);

    // Create printable HTML
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>${title}</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #0066cc; color: white; padding: 10px; text-align: left; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
    <table>
        <thead>
            <tr>
                ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
        </thead>
        <tbody>
            ${data.map(row => `
                <tr>
                    ${headers.map(h => `<td>${row[h] || ''}</td>`).join('')}
                </tr>
            `).join('')}
        </tbody>
    </table>
    <div class="footer">
        <p>This is an automated compliance report generated by the admin system.</p>
    </div>
</body>
</html>
    `;

    // Open print dialog
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(htmlContent);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
        }, 250);
    }
}

/**
 * Generate attestation pack (ZIP file)
 * Note: For production, integrate JSZip library
 */
export function generateAttestationPack(reports: { name: string; data: any[] }[], period: { start: string; end: string }): void {
    // Simplified implementation - exports each report as CSV
    console.log('Generating attestation pack for period:', period);

    reports.forEach(report => {
        if (report.data.length > 0) {
            exportToCSV(report.data, `${report.name}_${period.start}_to_${period.end}`);
        }
    });

    // console.log(`Attestation pack generated! ${reports.length} reports exported.`);
}

/**
 * Format date for filename
 */
export function formatDateForFilename(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}
